runtime: go
api_version: go1

default_expiration: "10m"

env_variables:
  GREETING: 'hello, world'

# More stuff here:
# https://cloud.google.com/appengine/docs/standard/go/config/appref

handlers:

# Find the static files in the 'static' directory
- url: /static
  redirect_http_response_code: 301
  secure: always
  static_dir: static

# The 'apple-touch-icon.png' file is also static
- url: /apple-touch-icon(-precomposed)?\.png
  redirect_http_response_code: 301
  secure: always
  static_files: static/favicon/apple-touch-icon.png
  upload: static/favicon/apple-touch-icon.png

# The 'browserconfig.xml' file is also static
- url: /browserconfig\.xml
  redirect_http_response_code: 301
  secure: always
  static_files: static/favicon/browserconfig.xml
  upload: static/favicon/browserconfig.xml

# The 'favicon.ico' file is also static
- url: /favicon\.ico
  redirect_http_response_code: 301
  secure: always
  static_files: static/favicon/favicon.ico
  upload: static/favicon/favicon.ico

### TODO: PCRE magic with capture groups(?) to reduce 2x favicon-XXxXX.png to 1x

# The 'favicon-16x16.png' file is also static
- url: /favicon-16x16\.png
  redirect_http_response_code: 301
  secure: always
  static_files: static/favicon/favicon-16x16.png
  upload: static/favicon/favicon-16x16.png

# The 'favicon-32x32.png' file is also static
- url: /favicon-32x32\.png
  redirect_http_response_code: 301
  secure: always
  static_files: static/favicon/favicon-32x32.png
  upload: static/favicon/favicon-32x32.png

# The 'robots.txt' file is also static
- url: /robots\.txt
  redirect_http_response_code: 301
  secure: always
  static_files: static/robots.txt
  upload: static/robots.txt

# All other URLs are handled by the Go application script
- url: /.*
  redirect_http_response_code: 301
  secure: always
  script: _go_app
