service: hugo

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: hugo/public/index.html
  upload: hugo/public/index.html

- url: /(.*)
  static_files: hugo/public/\1
  upload: hugo/public/(.*)
