### Just do this instead
# gsutil -m rsync -d -J -r . gs://hugo.jameslucktaylor.info

service: hugo

runtime: go
api_version: go1

handlers:
- url: /hugo
  redirect_http_response_code: 301
  secure: always
  static_dir: hugo/public

# Find the static files in the 'static' directory
- url: /static
  http_headers:
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    X-Content-Type-Options: nosniff
  redirect_http_response_code: 301
  secure: always
  static_dir: static

# Static favicon asset files
- url: /(browserconfig\.xml|favicon\.ico)$
  http_headers:
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    X-Content-Type-Options: nosniff
  redirect_http_response_code: 301
  secure: always
  static_files: static/favicon/\1
  upload: static/favicon/(browserconfig\.xml|favicon\.ico)$

# The 2x Apple icon files are also static (and identical)
- url: /apple-touch-icon(-precomposed)?\.png$
  http_headers:
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    X-Content-Type-Options: nosniff
  redirect_http_response_code: 301
  secure: always
  static_files: static/favicon/apple-touch-icon.png
  upload: static/favicon/apple-touch-icon.png

# The 'robots.txt' file is also static
- url: /robots\.txt$
  http_headers:
    Cache-Control: no-cache, no-store, must-revalidate
    Pragma: no-cache
    X-Content-Type-Options: nosniff
  redirect_http_response_code: 301
  secure: always
  static_files: static/robots.txt
  upload: static/robots.txt

# All other URLs are handled by the Go application script
- url: /go/.*
  redirect_http_response_code: 301
  secure: always
  script: _go_app

env_variables:
  GREETING: 'Hello, world! o/'
