runtime: go
api_version: go1

default_expiration: "10m"

env_variables:
  GREETING: 'hello, world'

# More stuff here:
# https://cloud.google.com/appengine/docs/standard/go/config/appref

handlers:

# Find the static files in the 'static' directory
- url: /static
  redirect_http_response_code: 301
  secure: always
  static_dir: static

# The 'robots.txt' file is also static
- url: /robots.txt
  redirect_http_response_code: 301
  secure: always
  static_files: static/robots.txt
  upload: static/robots.txt

# All other URLs are handled by the Go application script
- url: /.*
  redirect_http_response_code: 301
  secure: always
  script: _go_app
